{% set data = load_setuptools() %}

package:
    name: conda-build-all
    version: {{data.get('version')}}

source:
    path: ../

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - conda
        - conda-build >=1.20.2
        - anaconda-client
        - mock  # [py<33]

test:
  imports:
    - conda_build_all
  commands:
    - conda buildall --help
    - conda-buildall --version
    - conda build-all --help

about:
  license: BSD-3
  home: https://github.com/scitools/conda-build-all
